name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      ORG_GRADLE_PROJECT_FILM_TIME_TMDB_API_KEY: ${{ secrets.ORG_GRADLE_PROJECT_FILM_TIME_TMDB_API_KEY }}

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Check code style with Spotless
      run: ./gradlew spotlessCheck

    - name: Build with Gradle
      run: ./gradlew build
