name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    name: "Check code style and build"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      ORG_GRADLE_PROJECT_FILM_TIME_TMDB_API_KEY: ${{ secrets.ORG_GRADLE_PROJECT_FILM_TIME_TMDB_API_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'zulu'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Check build-logic
      run: ./gradlew check -p ./gradle/build-logic

    - name: Check code style with Spotless
      run: ./gradlew spotlessCheck --no-configuration-cache

    - name: Build with Gradle
      run: ./gradlew build
